sensors:
  addresses: [0x40, 0x41, 0x44, 0x45]

game:
  refresh_rate: 0.5                   # frequenza di refresh del gioco
  duration: 60                        # durata del gioco
  voltage_activation_threshold: 3.0   # volt di attivazione partita
  time_activation_threshold: 5        # secondi di attivazione partita
  cooldown: 10                        # secondi prima di cancellare il gioco

database:
  url: http://localhost:8086
  token: fcLoscx68fhFp_Bd3LT3Qac24j9AlGIK9SbUHpoyGH0Fbcwi5Ccyt0QJrxhAEVV11eWq-n4Y9VqeAOjIBZgm_A==
  org: PedalPower
  bucket: pedalpower

logging:
  level: INFO