sensors:
  addresses: [0x40, 0x41, 0x44, 0x45]

game:
  duration: 60                        # durata del gioco
  voltage_activation_threshold: 3.0   # volt di attivazione partita
  time_activation_threshold: 5        # secondi di attivazione partita

database:
  host: localhost
  port: 8086
  db_name: bike_game
  measurement: energy

logging:
  level: INFO